### ISSUE TITLE
Support for redirectTarget

### ISSUE THREAD

**Issue by voghan** [adobe/aem-angular-editable-components#25]
I'm working on an Angular SPA prject and I have not found a work around for pages setup in AEM as directs.  We have a couple pages that are used for organizing child pages.  The parent page redirects to one of the child pages but it seems the SPA editor routing strategy doesn't support redirecting routes.

**Comment by niekraaijmakers** [comment]
Okay, I don't know too much about Angular etc, but can we get a bit more information on this.. some screenshots from the model JSON etc, maybe a little bit of the project source code where the routing is used etc?

**Comment by voghan** [comment]
So I ended up solving my problem. I've updated page.component.ts to include a check for redirect target in page properties.

`this.modelManagerService
      .getData({ path: this.route.snapshot.data.path })
      .then(data => {
        this.path = data[Constants.PATH_PROP];
        this.items = data[Constants.ITEMS_PROP];
        this.itemsOrder = data[Constants.ITEMS_ORDER_PROP];
        this.redirectTarget = data[this.REDIRECT_PATH];
        if (this.redirectTarget) {
          this.router.navigate([this.redirectTarget.page.path]);
        }
      });`

**Comment by pfauchere** [comment]
For an improvement related to the current issue to make it to the SDK, we would need more info.
