### ISSUE TITLE
[bug] Anchor link hangs browser

### ISSUE THREAD

**Issue by voghan** [adobe/aem-angular-editable-components#33]
**Describe the bug**
When navigating to or on a page using an anchor link, (ie /content/our-site/home#benefits)  , the page hangs for several minutes before loading and scrolling to the element with the anchor id.

**Package version**
    "@adobe/cq-angular-editable-components": "^2.0.2"

**To Reproduce**
<a routerLink="./" fragment="benefits">go to benefits</a>
<div id="benefits">some content here</div>

**Expected behavior**
Upon clicking the link, the webpage scrolls to the element with the matching anchor id.

**Comment by pfauchere** [comment]
Created an internal issue. Ref: CQ-4311165

**Comment by patch-e** [comment]
I found the issue to be a poorly performing regex that gets into a recursive loop in PathUtils.ts in cq-spa-page-model-manager (now called aem-spa-page-model-manager) when a fragment is on the path coming into the function.

https://github.com/adobe/aem-spa-page-model-manager/blob/3ea346c82a107cef310d37d738e267d895fe805a/src/PathUtils.ts#L245

Failing test case with the regex:
```
var path = '/content/xyz/en/website/home/products-we-offer/products-xyz/xyz#detail.model';  
var match = /^((?:[/a-zA-Z0-9:_-]*)+)(?:\.?)([a-zA-Z0-9._-]*)(?:\/?)([a-zA-Z0-9/._-]*)(?:\??)([a-zA-Z0-9=&]*)$/g.exec(path);  
console.log(match);
```

Passing test case with the regex:
```
var path = '/content/xyz/en/website/home/products-we-offer/products-xyz/xyz.model';  
var match = /^((?:[/a-zA-Z0-9:_-]*)+)(?:\.?)([a-zA-Z0-9._-]*)(?:\/?)([a-zA-Z0-9/._-]*)(?:\??)([a-zA-Z0-9=&]*)$/g.exec(path);  
console.log(match);
```

![screenshot-ff-console](https://user-images.githubusercontent.com/1403821/102219900-160b4100-3eae-11eb-976f-243b12e05f8f.png)

**Comment by pfauchere** [comment]
I think that the following URL is illegitimately generated:

`/content/xyz/en/website/home/products-we-offer/products-xyz/xyz#detail.model.json`

We should instead get:

'/content/xyz/en/website/home/products-we-offer/products-xyz/xyz.model.json`

I don't think that the model manager should attempt to fetch the model of anchors. In such a case we are interested in the model of the page. Unless there is a use-case I don't yet see, we may want to strip or ignore the anchor chunk of the URL when generating the URL to fetch the model in [0]. 

[0] https://github.com/adobe/aem-spa-page-model-manager/blob/master/src/ModelManager.ts#L535

**Comment by pfauchere** [comment]
BTW the issue relates to the page model manager repository. Let's follow-up their

https://github.com/adobe/aem-spa-page-model-manager/issues/39
